name: xUnit.net Analyzers CI Build
on:
  push:
    branches:
      - master

jobs:
  build-unix:
    name: "CI Build"
    runs-on: ubuntu-18.04
    steps:
      - name: Clone source
        uses: actions/checkout@v1

      - name: Install .NET Core SDK 2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.805

      - name: Install .NET Core SDK 3.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.0.103

      - name: Enable .NET Core SxS
        run: rsync -a ${DOTNET_ROOT/3.0.103/2.1.805}/* $DOTNET_ROOT/

      - name: Get build information
        run: dotnet tool restore && dotnet nbgv cloud --all-vars

      - name: "Build target: CI"
        env:
          PublishToken: ${{ secrets.PublishToken }}
          SignClientUser: ${{ secrets.SignClientUser }}
          SignClientSecret: ${{ secrets.SignClientSecret }}
        run: bash ./build CI

      - name: "Upload artifact: test"
        uses: actions/upload-artifact@v1
        with:
          name: test
          path: artifacts/test
        if: always()

      - name: Slack notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: "CI Build: xunit.analyzers"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SlackWebhookUrl }}
        if: always()
